### ISSUE TITLE
Can not delete extra notifications

### ISSUE THREAD

**Issue by mwatty7** [MikeElofson/FoodAlerts#2]
In Current Alerts 
user matt watt has an extra alert that is not valid.

the user can not delete the extra alert

![image](https://cloud.githubusercontent.com/assets/13875927/9368045/c8088960-4686-11e5-9ed4-96567aa6a35f.png)

**Comment by MikeElofson** [comment]
This issue appears to be related to: https://github.com/MikeElofson/FoodAlertsCal/issues/4

Alerts with normal strings are able to be deleted fine.

**Comment by MikeElofson** [comment]
Added validation to check if the format is a valid email format or phone number. Also restricted use of single quotes (') in the alert address, as that seemed to cause issues.

https://github.com/MikeElofson/FoodAlerts/commit/d54f2bf716016f40745d563d3722fbf12b5cae04
