### ISSUE TITLE
Last alerts on home page not ordered

### ISSUE THREAD

**Issue by MikeElofson** [MikeElofson/FoodAlerts#8]
Ordering of the alerts on the home page appear to be completely random. They should be ordered newest to oldest.

May also want to limit how many results appear on the page. List could possibly become very long

**Comment by MattNohelty** [comment]
fixed and added a chart

**Comment by MikeElofson** [comment]
Nice sounds good. Chart for the index page? I was gunna get started on
admin stuff but got distracted by video games haha.
